In [4]:
import pandas as pd

In [5]:
df = pd.read_csv('/Users/ignaciolazarovalganon/Downloads/GitHub/AIRBNB_Project/app_predict/listings_knn.csv')

In [6]:
df['room_type_x'].unique()

array(['Private room', 'Entire home/apt', 'Hotel room', 'Shared room'],
      dtype=object)

In [7]:
df.head()

,host_id_x,neighbourhood,latitude_x,longitude_x,room_type_x,price_x,number_of_reviews_x,reviews_per_month_x,availability_365_x,accommodates,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,review_scores_rating,instant_bookable
0,3047.0,VIII Appia Antica,41.871360,12.482150,Private room,75.0,7.0,0.07,358.0,1.0,within a few hours,98.0,3.0,0.0,4.80,0.0
1,3504.0,I Centro Storico,41.895000,12.491170,Entire home/apt,90.0,21.0,0.14,130.0,4.0,within a day,100.0,10.0,1.0,4.53,0.0
2,44552.0,I Centro Storico,41.895447,12.491181,Entire home/apt,105.0,203.0,1.35,310.0,2.0,within a few hours,100.0,100.0,1.0,4.81,0.0
3,538724.0,I Centro Storico,41.887880,12.469750,Entire home/apt,110.0,389.0,2.60,266.0,6.0,within an hour,100.0,100.0,1.0,4.87,1.0
4,11756.0,II Parioli/Nomentano,41.925820,12.469280,Entire home/apt,121.0,59.0,0.38,303.0,6.0,within a few hours,100.0,82.0,1.0,4.91,0.0

In [8]:
from pycaret.regression import *

In [9]:
df.columns

Index(['host_id_x', 'neighbourhood', 'latitude_x', 'longitude_x',
       'room_type_x', 'price_x', 'number_of_reviews_x', 'reviews_per_month_x',
       'availability_365_x', 'accommodates', 'host_response_time',
       'host_response_rate', 'host_acceptance_rate', 'host_is_superhost',
       'review_scores_rating', 'instant_bookable'],
      dtype='object')

In [10]:
df_pred_new = df[['neighbourhood','room_type_x','price_x','accommodates',]]

In [11]:
df_pred_new.head()

          neighbourhood      room_type_x  price_x  accommodates
0     VIII Appia Antica     Private room     75.0           1.0
1      I Centro Storico  Entire home/apt     90.0           4.0
2      I Centro Storico  Entire home/apt    105.0           2.0
3      I Centro Storico  Entire home/apt    110.0           6.0
4  II Parioli/Nomentano  Entire home/apt    121.0           6.0

In [12]:
setup = setup(df_pred_new, target = "price_x")

In [13]:
best = compare_models()

In [14]:
gradient = create_model('gbr')

In [15]:
tuned_gradient = tune_model(gradient)

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

In [16]:
evaluate_model(tuned_gradient)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [17]:
final_gradient_best = finalize_model(tuned_gradient)

In [18]:
save_model(tuned_gradient, "ml_gradient_airbnb")

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(include=['accommodates'],
                                     transformer=SimpleImputer())),
                 ('categorical_imputer',
                  TransformerWrapper(include=['neighbourhood', 'room_type_x'],
                                     transformer=SimpleImputer(strategy='most_frequent'))),
                 ('onehot_encoding',
                  TransformerWrapper(include=['neighbourhood', 'room_type_x'],
                                     transformer=OneHotEncoder(cols=['neighbourhood',
                                                                     'room_type_x'],
                                                               handle_missing='return_nan',
                                                               use_cat_names=True))),
                 ('trained_model',
                  GradientBoostingRegressor(random_state=2114))]),
 'ml_gradient_airbnb.pkl')